name: Deploy Playwright Images to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - main
    paths:
      - apps/playwright-service-ts/**
  workflow_dispatch:

jobs:
  push-playwright-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './apps/playwright-service-ts'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Playwright Image'
        run: |
          docker build . --tag ghcr.io/majingyifighting/firecrawl-playwright:latest
          docker push ghcr.io/majingyifighting/firecrawl-playwright:latest 